In [140]:
# import io, os, sys, types

In [141]:
import numpy as np
import cv2
import matplotlib.pyplot
from pandas import *

In [142]:
def print_with_spacing(board):
    board = np.array(board)
    print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in board]))

In [143]:
def print_with_index(board):
    board = np.array(board)
    print(DataFrame(board))

In [144]:
# Creating the algorithm to find the shortest path and all possible paths 
# for the dots in the matrix or question board

def possible_paths(board , start , end):
    pass

In [145]:
board = [[-1]*10]*5

print_with_index(board)
print()
print_with_spacing(board)

   0  1  2  3  4  5  6  7  8  9
0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
2 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
3 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
4 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

-1	-1	-1	-1	-1	-1	-1	-1	-1	-1
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1


In [146]:
# print(makeGrid())

for i in range(4):
    print()
    print(makeGrid())


[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]

[[-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
